configure: add --with-pylint=[yes|no|maybe] defaulting to maybe
When set to no, don't run pylint from ./pylint, just exit
successfully.  When set to maybe, use dev/have-pylint to figure out if
pylint is available, and if so, run it, otherwise exit successfully
after describing the situation.  When set to yes, always try to run
pylint.

This may be useful more generally, but in particular, it makes it
possible to run this:

  ./configure --with-pylint=maybe
  make check-both

in situations where pylint is available for say python 3, but not
python 2.

Signed-off-by: Rob Browning <rlb@defaultvalue.org>
Tested-by: Rob Browning <rlb@defaultvalue.org>

diff --git a/pylint b/pylint
--- a/pylint
+++ b/pylint
@@ -1,8 +1,35 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 # Changes here might also be appropriate for ./pytest
 
 set -eu
+
+with_pylint=$(cat config/config.var/with-pylint)
+
+case "$with_pylint" in
+    yes) ;;
+    no)
+        echo "./pylint: doing nothing given ./configure --with-pylint=no" 1>&2
+        exit 0
+        ;;
+    maybe)
+        rc=0
+        dev/have-pylint || rc=$?
+        case "$rc" in
+            0) ;;
+            1)
+                echo "./pylint: doing nothing (pylint not found)" 1>&2
+                exit 0
+                ;;
+            *) exit "$rc" ;;
+        esac
+        ;;
+    *)
+        printf "./pylint: unexpected config/config.var/with-pylint value %q\n" \
+               "$with_pylint" 1>&2
+        exit 2
+        ;;
+esac
 
 script_home="$(cd "$(dirname "$0")" && pwd -P)"
 testlibdir="$script_home/test/lib"
