Allow multiple manpage sections (not just 1)
Rename the manpages to include the section number and adjust
everything to handle that.

Thanks to Johannes Berg for pointing out the omission and providing an
earlier, slightly different formulation.

Signed-off-by: Rob Browning <rlb@defaultvalue.org>
Tested-by: Rob Browning <rlb@defaultvalue.org>
(cherry picked from commit 69dfa91231be5a6eb6fd650f18c1f8e0b80eb43f)

diff --git a/dev/update-doc-branches b/dev/update-doc-branches
--- a/dev/update-doc-branches
+++ b/dev/update-doc-branches
@@ -12,7 +12,11 @@ test "$#" -eq 2
 man_ref="$1"
 html_ref="$2"
 
-git diff-index --quiet HEAD --  # no uncommitted changes
+if ! git diff-index --quiet HEAD --; then
+    echo 'error: uncommitted changes'
+    exit 2
+fi
+
 git rev-parse --verify "$man_ref"
 git rev-parse --verify "$html_ref"
 echo "$man_ref" | grep -qE '^refs/heads'
@@ -31,7 +35,7 @@ for fmt in man html; do
         base="$(basename "$f" .md)"
         if test "$fmt" = man; then
             ref="$man_ref"
-            GIT_INDEX_FILE="$tmpidx" git add -f "Documentation/$base.1"
+            GIT_INDEX_FILE="$tmpidx" git add -f "Documentation/$base"
         else
             ref="$html_ref"
             GIT_INDEX_FILE="$tmpidx" git add -f "Documentation/$base.html"
