test: avoid potential SIGPIPE failures via head -1
"something | head -1" can fail if head exits "early", causing
something to receive a SIGPIPE (and coreutils head may).

Add a WVPIPE that acts exactly like WVPASS, except that it ignores an
exit status of 128 + SIGPIPE. This is bash specific because bash
promises that the exit status of a command that's terminated by a
signal will be 128 + signal value.

Use WVPIPE to avoid the failures, and add a btl-ent-oid to extract the
oid from a git ls-tree line to be more descriptive and replace
multiple cut invocations.

Thanks to Nathaniel Hourt for reporting the problem and Nathaniel
Hourt and Johannes Berg for tracking down the cause, and Joannes Berg
for proposing the WVPIPE approach.

Signed-off-by: Rob Browning <rlb@defaultvalue.org>
Tested-by: Rob Browning <rlb@defaultvalue.org>

diff --git a/test/ext/test-walk-object-order b/test/ext/test-walk-object-order
--- a/test/ext/test-walk-object-order
+++ b/test/ext/test-walk-object-order
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
-. ./wvtest-bup.sh
+. ./wvtest-bup.sh || exit $?
+. test/lib/btl.sh || exit $?
 
 set -o pipefail
 
@@ -30,10 +31,10 @@ src_oid="$(WVPASS git rev-parse src)" || exit $?
 # post-order traversal would fetch/store (ordering for a/ is 3 2 1
 # .bupm), leaving the destination with an incomplete a/.
 
-WVPASS git ls-tree src:a | WVPASS cut -d' ' -f 3 \
-    | WVPASS cut -b -40 | WVPASS head -1 > bupm-oid
+bupm_oid="$(WVPIPE git ls-tree src:a | WVPASS head -1 | WVPASS btl-ent-oid)" \
+    || exit $?
 WVPASS cp -a bup bup-missing
-WVPASS "$top/dev/perforate-repo" --drop-oids bup-missing < bupm-oid
+echo "$bupm_oid" | WVPASS "$top/dev/perforate-repo" --drop-oids bup-missing
 
 # Now fetch from the broken repo, make sure that creates a broken src,
 # then fetch again from the complete repo and make sure that produces
